// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eubLNIbvXrB9nWTfCihn08PM9odOoX8',
    appId: '1:43237803567:web:01632a0b87385a18c228da',
    messagingSenderId: '43237803567',
    projectId: 'illinoisridesharemobile',
    authDomain: 'illinoisridesharemobile.firebaseapp.com',
    storageBucket: 'illinoisridesharemobile.appspot.com',
    measurementId: 'G-Z23K4P3YLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYbRRkIA1aVok1Cayp7-lrv5tDUh6hnY',
    appId: '1:43237803567:android:8e6f2d5f38f315ecc228da',
    messagingSenderId: '43237803567',
    projectId: 'illinoisridesharemobile',
    storageBucket: 'illinoisridesharemobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRT8uhL25Y6guGFZl6_jhHtL6WhalN5o',
    appId: '1:43237803567:ios:f5a67c1764fe48b2c228da',
    messagingSenderId: '43237803567',
    projectId: 'illinoisridesharemobile',
    storageBucket: 'illinoisridesharemobile.appspot.com',
    iosClientId: '43237803567-5hd3rnl58ug5d2bmddfia7gbr6r0v06j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRT8uhL25Y6guGFZl6_jhHtL6WhalN5o',
    appId: '1:43237803567:ios:f5a67c1764fe48b2c228da',
    messagingSenderId: '43237803567',
    projectId: 'illinoisridesharemobile',
    storageBucket: 'illinoisridesharemobile.appspot.com',
    iosClientId: '43237803567-5hd3rnl58ug5d2bmddfia7gbr6r0v06j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideshare',
  );
}
